export function ReturnSkins() {
    const skinsSrc = [
        { src: 'assets/BenSkins/BenFigure.png', description: "Standard Ben" },
        { src: 'assets/BenSkins/EmoBen.png', description: "Emo Ben :(" },
        { src: 'assets/BenSkins/LeanBen.png', description: "Lean Ben" },
        { src: 'assets/BenSkins/PencilBen.png', description: "Nerd Ben" },
        { src: 'assets/BenSkins/StonedBen.png', description: "Kiffer Ben v1" },
        { src: 'assets/BenSkins/MusicBen.png', description: "Musik Ben" },
        { src: 'assets/BenSkins/LegoBen.png', description: "Lego Ben" },
        { src: 'assets/BenSkins/RobloxBen.png', description: "Roblox Ben" },
        { src: 'assets/BenSkins/PartyBen.png', description: "Happy New Year 2008 Ben" },
        { src: 'assets/BenSkins/SenfBen.png', description: "Senf Ben" },
        { src: 'assets/BenSkins/BenBanane.png', description: "Bananen Ben" },
        { src: 'assets/BenSkins/AmericanBen.png', description: "Uncle Ben" },
        { src: 'assets/BenSkins/BratwurstBen.png', description: "Bratwurst Ben" },
        { src: 'assets/BenSkins/BenKatze.png', description: "Katzen Ben" },
        { src: 'assets/BenSkins/BenFortnite.png', description: "Fortnite Ben" },
        { src: 'assets/BenSkins/BenKawasaki.png', description: "Kawasaki Ben" },
        { src: 'assets/BenSkins/BenTerror.png', description: "Terror Ben" },
        { src: 'assets/BenSkins/BongBen.png', description: "Kiffer Ben v2" },
        { src: 'assets/BenSkins/BenMan.png', description: "Benman" },
        { src: 'assets/BenSkins/PizzaBen.png', description: "Pizza Ben" },
        { src: 'assets/BenSkins/WasJucktMichDasBen.png', description: "Was juckt mich das? Ben" },
        { src: 'assets/BenSkins/WtfBen.png', description: "Pedo Ben" },
        { src: 'assets/BenSkins/MaidBen.png', description: "Fabrice" },
        { src: 'assets/BenSkins/LeonLoveBen.png', description: "Love Leon Ben" },
        { src: 'assets/BenSkins/WastelandBen.png', description: "Wasteland Ben" },
        { src: 'assets/BenSkins/SnakeBen.png', description: "Schlangen Ben" },
        { src: 'assets/BenSkins/IronBen.png', description: "Ironben" },
        { src: 'assets/BenSkins/ZombieBen.png', description: "Zombie Ben" },
        { src: 'assets/BenSkins/CrazyBen.png', description: "??? Ben" },
        { src: 'assets/BenSkins/PoliceBen.png', description: "Polizei Ben" },
        { src: 'assets/BenSkins/CrackBen.png', description: "Vercrackter Ben" },
        { src: 'assets/BenSkins/VerklebtBen.png', description: "Verklebter Ben" },
        { src: 'assets/BenSkins/GangsterBen.png', description: "Gangster Ben" },
        { src: 'assets/BenSkins/RichBen.png', description: "Reicher Ben" },
        { src: 'assets/BenSkins/EvilBen.png', description: "Evil Ben" },
        { src: 'assets/BenSkins/GoldenBen.png', description: "Golden Ben" },
        { src: 'assets/BenSkins/DiamondBen.png', description: "Diamant Ben" },
        { src: 'assets/BenSkins/UltimateBen.png', description: "Ultimate Ben" },
        { src: 'assets/BenSkins/TheOneAndOnlyBen.png', description: "The One and Only Ben" },
    ]

    return skinsSrc;
}